import "dotenv/config";
import { PrismaClient } from "../src/generated/prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter });

const countryNames: Record<string, string> = {
  AFN: "Afghanistan",
  ALL: "Albania",
  DZD: "Algeria",
  USD: "United States",
  EUR: "Eurozone",
  AOA: "Angola",
  XCD: "East Caribbean States",
  ARS: "Argentina",
  AMD: "Armenia",
  AWG: "Aruba",
  AUD: "Australia",
  AZN: "Azerbaijan",
  BSD: "Bahamas",
  BHD: "Bahrain",
  BDT: "Bangladesh",
  BBD: "Barbados",
  BYN: "Belarus",
  BYR: "Belarus",
  BZD: "Belize",
  XOF: "West African States",
  BMD: "Bermuda",
  BTN: "Bhutan",
  INR: "India",
  BOB: "Bolivia",
  BAM: "Bosnia and Herzegovina",
  BWP: "Botswana",
  NOK: "Norway",
  BRL: "Brazil",
  BND: "Brunei",
  XAF: "Central African States",
  BIF: "Burundi",
  CVE: "Cape Verde",
  KHR: "Cambodia",
  CAD: "Canada",
  KYD: "Cayman Islands",
  CLF: "Chile",
  CLP: "Chile",
  CNY: "China",
  CNH: "China (offshore)",
  COP: "Colombia",
  KMF: "Comoros",
  CDF: "Congo",
  NZD: "New Zealand",
  CRC: "Costa Rica",
  CUC: "Cuba",
  CUP: "Cuba",
  XCG: "Caribbean",
  CZK: "Czech Republic",
  DKK: "Denmark",
  DJF: "Djibouti",
  DOP: "Dominican Republic",
  EGP: "Egypt",
  SVC: "El Salvador",
  ERN: "Eritrea",
  ETB: "Ethiopia",
  FKP: "Falkland Islands",
  FJD: "Fiji",
  XPF: "French Polynesia",
  GMD: "Gambia",
  GEL: "Georgia",
  GHS: "Ghana",
  GIP: "Gibraltar",
  GTQ: "Guatemala",
  GBP: "United Kingdom",
  GNF: "Guinea",
  GYD: "Guyana",
  HTG: "Haiti",
  HKD: "Hong Kong",
  HUF: "Hungary",
  ISK: "Iceland",
  IDR: "Indonesia",
  XDR: "International Monetary Fund",
  IRR: "Iran",
  IQD: "Iraq",
  ILS: "Israel",
  JMD: "Jamaica",
  JPY: "Japan",
  JOD: "Jordan",
  KZT: "Kazakhstan",
  KES: "Kenya",
  KPW: "North Korea",
  KRW: "South Korea",
  KWD: "Kuwait",
  KGS: "Kyrgyzstan",
  LAK: "Laos",
  LBP: "Lebanon",
  LSL: "Lesotho",
  ZAR: "South Africa",
  LRD: "Liberia",
  LYD: "Libya",
  CHF: "Switzerland",
  MOP: "Macau",
  MKD: "North Macedonia",
  MGA: "Madagascar",
  MWK: "Malawi",
  MYR: "Malaysia",
  MVR: "Maldives",
  MUR: "Mauritius",
  MRU: "Mauritania",
  MXN: "Mexico",
  MDL: "Moldova",
  MNT: "Mongolia",
  MAD: "Morocco",
  MZN: "Mozambique",
  MMK: "Myanmar",
  NAD: "Namibia",
  NPR: "Nepal",
  NIO: "Nicaragua",
  NGN: "Nigeria",
  OMR: "Oman",
  PKR: "Pakistan",
  PAB: "Panama",
  PGK: "Papua New Guinea",
  PYG: "Paraguay",
  PEN: "Peru",
  PHP: "Philippines",
  PLN: "Poland",
  QAR: "Qatar",
  RON: "Romania",
  ROL: "Romania",
  RUB: "Russia",
  RWF: "Rwanda",
  SHP: "Saint Helena",
  STN: "São Tomé and Príncipe",
  STD: "São Tomé and Príncipe",
  SAR: "Saudi Arabia",
  RSD: "Serbia",
  SCR: "Seychelles",
  SLE: "Sierra Leone",
  SLL: "Sierra Leone",
  SGD: "Singapore",
  SBD: "Solomon Islands",
  SOS: "Somalia",
  LKR: "Sri Lanka",
  SDG: "Sudan",
  SRD: "Suriname",
  SZL: "Eswatini",
  SEK: "Sweden",
  SYP: "Syria",
  TWD: "Taiwan",
  TJS: "Tajikistan",
  TZS: "Tanzania",
  THB: "Thailand",
  TTD: "Trinidad and Tobago",
  TND: "Tunisia",
  TRY: "Turkey",
  TRL: "Turkey",
  TMT: "Turkmenistan",
  UGX: "Uganda",
  UAH: "Ukraine",
  AED: "United Arab Emirates",
  UYU: "Uruguay",
  UZS: "Uzbekistan",
  VUV: "Vanuatu",
  VES: "Venezuela",
  VND: "Vietnam",
  YER: "Yemen",
  ZMW: "Zambia",
  ZMK: "Zambia",
  ZWL: "Zimbabwe",
  CYP: "Cyprus",
  EEK: "Estonia",
  LTL: "Lithuania",
  LVL: "Latvia",
  MTL: "Malta",
  SIT: "Slovenia",
  SKK: "Slovakia",
  HRK: "Croatia",
  ANG: "Netherlands Antilles",
  BGN: "Bulgaria",
  XAU: "Gold",
  XAG: "Silver",
  BTC: "Bitcoin",
  GGP: "Guernsey",
  IMP: "Isle of Man",
  JEP: "Jersey",
};

const currencyNames: Record<string, string> = {
  AFN: "Afghani",
  ALL: "Lek",
  DZD: "Algerian Dinar",
  USD: "US Dollar",
  EUR: "Euro",
  AOA: "Kwanza",
  XCD: "East Caribbean Dollar",
  ARS: "Argentine Peso",
  AMD: "Armenian Dram",
  AWG: "Aruban Florin",
  AUD: "Australian Dollar",
  AZN: "Azerbaijanian Manat",
  BSD: "Bahamian Dollar",
  BHD: "Bahraini Dinar",
  BDT: "Taka",
  BBD: "Barbados Dollar",
  BYN: "Belarussian Ruble",
  BYR: "Belarussian Ruble (old)",
  BZD: "Belize Dollar",
  XOF: "CFA Franc BCEAO",
  BMD: "Bermudian Dollar",
  BTN: "Ngultrum",
  INR: "Indian Rupee",
  BOB: "Boliviano",
  BAM: "Convertible Mark",
  BWP: "Pula",
  NOK: "Norwegian Krone",
  BRL: "Brazilian Real",
  BND: "Brunei Dollar",
  XAF: "CFA Franc BEAC",
  BIF: "Burundi Franc",
  CVE: "Cabo Verde Escudo",
  KHR: "Riel",
  CAD: "Canadian Dollar",
  KYD: "Cayman Islands Dollar",
  CLF: "Unidad de Fomento",
  CLP: "Chilean Peso",
  CNY: "Yuan Renminbi",
  CNH: "Chinese Yuan (offshore)",
  COP: "Colombian Peso",
  KMF: "Comoro Franc",
  CDF: "Congolese Franc",
  NZD: "New Zealand Dollar",
  CRC: "Costa Rican Colon",
  CUC: "Peso Convertible",
  CUP: "Cuban Peso",
  XCG: "Caribbean Guilder",
  CZK: "Czech Koruna",
  DKK: "Danish Krone",
  DJF: "Djibouti Franc",
  DOP: "Dominican Peso",
  EGP: "Egyptian Pound",
  SVC: "El Salvador Colon",
  ERN: "Nakfa",
  ETB: "Ethiopian Birr",
  FKP: "Falkland Islands Pound",
  FJD: "Fiji Dollar",
  XPF: "CFP Franc",
  GMD: "Dalasi",
  GEL: "Lari",
  GHS: "Ghana Cedi",
  GIP: "Gibraltar Pound",
  GTQ: "Quetzal",
  GBP: "Pound Sterling",
  GNF: "Guinea Franc",
  GYD: "Guyana Dollar",
  HTG: "Gourde",
  HKD: "Hong Kong Dollar",
  HUF: "Forint",
  ISK: "Iceland Krona",
  IDR: "Rupiah",
  XDR: "Special Drawing Rights",
  IRR: "Iranian Rial",
  IQD: "Iraqi Dinar",
  ILS: "New Israeli Sheqel",
  JMD: "Jamaican Dollar",
  JPY: "Yen",
  JOD: "Jordanian Dinar",
  KZT: "Tenge",
  KES: "Kenyan Shilling",
  KPW: "North Korean Won",
  KRW: "Won",
  KWD: "Kuwaiti Dinar",
  KGS: "Som",
  LAK: "Kip",
  LBP: "Lebanese Pound",
  LSL: "Loti",
  ZAR: "Rand",
  LRD: "Liberian Dollar",
  LYD: "Libyan Dinar",
  CHF: "Swiss Franc",
  MOP: "Pataca",
  MKD: "Denar",
  MGA: "Malagasy Ariary",
  MWK: "Kwacha",
  MYR: "Malaysian Ringgit",
  MVR: "Rufiyaa",
  MUR: "Mauritius Rupee",
  MRU: "Ouguiya",
  MXN: "Mexican Peso",
  MDL: "Moldovan Leu",
  MNT: "Tugrik",
  MAD: "Moroccan Dirham",
  MZN: "Mozambique Metical",
  MMK: "Kyat",
  NAD: "Namibia Dollar",
  NPR: "Nepalese Rupee",
  NIO: "Cordoba Oro",
  NGN: "Naira",
  OMR: "Rial Omani",
  PKR: "Pakistan Rupee",
  PAB: "Balboa",
  PGK: "Kina",
  PYG: "Guarani",
  PEN: "Nuevo Sol",
  PHP: "Philippine Peso",
  PLN: "Zloty",
  QAR: "Qatari Rial",
  RON: "Romanian Leu",
  ROL: "Romanian Leu (old)",
  RUB: "Russian Ruble",
  RWF: "Rwanda Franc",
  SHP: "Saint Helena Pound",
  STN: "Dobra",
  STD: "Dobra (old)",
  SAR: "Saudi Riyal",
  RSD: "Serbian Dinar",
  SCR: "Seychelles Rupee",
  SLE: "Leone",
  SLL: "Leone (old)",
  SGD: "Singapore Dollar",
  SBD: "Solomon Islands Dollar",
  SOS: "Somali Shilling",
  LKR: "Sri Lanka Rupee",
  SDG: "Sudanese Pound",
  SRD: "Surinam Dollar",
  SZL: "Lilangeni",
  SEK: "Swedish Krona",
  SYP: "Syrian Pound",
  TWD: "New Taiwan Dollar",
  TJS: "Somoni",
  TZS: "Tanzanian Shilling",
  THB: "Baht",
  TTD: "Trinidad and Tobago Dollar",
  TND: "Tunisian Dinar",
  TRY: "Turkish Lira",
  TRL: "Turkish Lira (old)",
  TMT: "Turkmenistan New Manat",
  UGX: "Uganda Shilling",
  UAH: "Hryvnia",
  AED: "UAE Dirham",
  UYU: "Peso Uruguayo",
  UZS: "Uzbekistan Sum",
  VUV: "Vatu",
  VES: "Bolivar Soberano",
  VND: "Dong",
  YER: "Yemeni Rial",
  ZMW: "Zambian Kwacha",
  ZMK: "Zambian Kwacha (old)",
  ZWL: "Zimbabwe Dollar",
  // Legacy / other
  CYP: "Cypriot Pound",
  EEK: "Estonian Kroon",
  LTL: "Lithuanian Litas",
  LVL: "Latvian Lats",
  MTL: "Maltese Lira",
  SIT: "Slovenian Tolar",
  SKK: "Slovak Koruna",
  HRK: "Croatian Kuna",
  ANG: "Netherlands Antillean Guilder",
  BGN: "Bulgarian Lev",
  // Precious metals & special
  XAU: "Gold (troy ounce)",
  XAG: "Silver (troy ounce)",
  BTC: "Bitcoin",
  // Crown dependencies
  GGP: "Guernsey Pound",
  IMP: "Isle of Man Pound",
  JEP: "Jersey Pound",
};

async function main() {
  const countries = await prisma.currency.findMany();
  console.log(`Updating names for ${countries.length} countries...`);

  const toUpdate = countries.filter((c) => currencyNames[c.countryCode] || countryNames[c.countryCode]);
  const skipped = countries.filter((c) => !currencyNames[c.countryCode] && !countryNames[c.countryCode]);

  skipped.forEach((c) => console.warn(`No name found for: ${c.countryCode}`));

  await Promise.all(
    toUpdate.map((c) =>
      prisma.currency.update({
        where: { id: c.id },
        data: {
          currencyName: currencyNames[c.countryCode],
          countryName: countryNames[c.countryCode],
        },
      })
    )
  );

  console.log(`Done! Updated: ${toUpdate.length}, Skipped: ${skipped.length}`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
